[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = "core.lua"
before = "functions/UI_definitions.lua"
name = "collectionsearchbar"

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "local t = create_UIBox_generic_options({ back_func = G.STAGE == G.STAGES.RUN and 'options' or 'exit_overlay_menu', contents = {"
position = 'at'
payload = "local t = create_UIBox_generic_options({ back_func = G.STAGE == G.STAGES.RUN and 'options' or 'exit_overlay_menu', current_menu = 'your_collection', contents = {"
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "{n=G.UIT.C, config={align = \"cm\", minh = 1,r = 0.2, padding = 0.2, minw = 1, colour = args.colour or G.C.L_BLACK}, nodes={"
position = 'after'
payload = "(args.current_menu == 'your_collection') and G.FUNCS.search_bar() or nil,"
match_indent = true